const showrooms = [
  {
    id: 1,
    url: "./home.png",
    area: "Parauna",
    landmarks: "near shiv mandir",
    house_no: "4A",
    pincode: 841219,
    city: "Hajipur",
    state: "Bihar",
    price: 10000,
    security: 5000,
    advancepay: "Full",
    rating: 4,
    review: 412,
  },
  {
    id: 2,
    url: "./home.png",
    area: "kharar",
    landmarks: "chandigarh university",
    house_no: "207",
    pincode: 140413,
    city: "Mohali",
    state: "Punjab",
    price: 10000,
    security: 5000,
    advancepay: "NO",
    rating: 3,
    review: 216,
  },
  {
    id: 3,
    url: "./home.png",
    area: "Parsa",
    landmarks: "near sbi bank",
    house_no: "102A",
    pincode: 841218,
    city: "Parsa",
    state: "Bihar",
    price: 10000,
    security: 5000,
    advancepay: "Half",
    rating: 4.5,
    review: 345,
  },
];

export default showrooms;
