const showrooms = [
  {
    id: 1,
    url: "../home.png",
    address: {
      area: "Parauna",
      landmarks: "near shiv mandir",
      house_no: "4A",
      pincode: 841219,
      city: "Hajipur",
      state: "Bihar",
    },
    roomtype: "Flat",
    price: 10000,
    security: 5000,
    advancepay: "Full",
    rating: 4,
    review: 412,
  },
  {
    id: 2,
    url: "../home.png",
    address: {
      area: "kharar",
      landmarks: "chandigarh university",
      house_no: "207",
      pincode: 140413,
      city: "Mohali",
      state: "Punjab",
    },
    roomtype: "Pg",
    price: 10000,
    security: 5000,
    advancepay: "NO",
    rating: 3,
    review: 216,
  },
  {
    id: 3,
    url: "../home.png",
    address: {
      area: "Parsa",
      landmarks: "near sbi bank",
      house_no: "102A",
      pincode: 841218,
      city: "Parsa",
      state: "Bihar",
    },
    roomtype: "Hostel",
    price: 10000,
    security: 5000,
    advancepay: "Half",
    rating: 4.5,
    review: 345,
  },
  {
    id: 4,
    url: "../home.png",
    address: {
      area: "Hajipur",
      landmarks: "Gandhi chak",
      house_no: "102A",
      pincode: 841220,
      city: "Hajipur",
      state: "Bihar",
    },
    roomtype: "Flat",
    price: 10000,
    security: 5000,
    advancepay: "Full",
    rating: 3.5,
    review: 545,
  },
  {
    id: 5,
    url: "../home.png",
    address: {
      area: "Kurji",
      landmarks: "Mahabir hospital",
      house_no: "12A",
      pincode: 840020,
      city: "Patna",
      state: "Bihar",
    },
    roomtype: "Flat",
    price: 15000,
    security: 8000,
    advancepay: "Half",
    rating: 4,
    review: 405,
  },
];

export default showrooms;
